"""Add PlayerProfile model

Revision ID: 03efa8451943
Revises: c02909d5f025
Create Date: 2024-12-07 15:41:53.604019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03efa8451943'
down_revision = 'c02909d5f025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('encounters', sa.Text(), nullable=True),
    sa.Column('npc_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('subspecies', sa.String(length=50), nullable=True),
    sa.Column('player_class', sa.String(length=50), nullable=False),
    sa.Column('background', sa.String(length=100), nullable=True),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('tool_proficiencies', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('saving_throws', sa.Text(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('weapons', sa.Text(), nullable=True),
    sa.Column('spells', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('campaign_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('narrative', sa.TEXT(), nullable=True),
    sa.Column('encounters', sa.TEXT(), nullable=True),
    sa.Column('npc_details', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player_profiles')
    op.drop_table('campaign_logs')
    # ### end Alembic commands ###
