"""add chat_messages table

Revision ID: 3769defdeb5c
Revises: e7950a440189
Create Date: 2026-06-07 12:39:58.308080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3769defdeb5c'
down_revision = 'e7950a440189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=1), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_npc_id'), ['npc_id'], unique=False)

    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.drop_column('chat_history')

    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_column('player_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_class', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_history', sa.TEXT(), nullable=True))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_npc_id'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
