"""Initial migration for NPC table

Revision ID: 39ca40c39f34
Revises: 
Create Date: 2024-12-07 00:13:30.631734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ca40c39f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('spells', sa.Text(), nullable=True),
    sa.Column('racial_features', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npc')
    # ### end Alembic commands ###
