"""add npc sheet column

Revision ID: 5e69fbb59c54
Revises: 3769defdeb5c
Create Date: 2026-06-08 16:24:33.085315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e69fbb59c54'
down_revision = '3769defdeb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet', sa.JSON(), nullable=True, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.drop_column('sheet')

    # ### end Alembic commands ###
