"""Add chat_history to NPC

Revision ID: c02909d5f025
Revises: 39ca40c39f34
Create Date: 2024-12-07 12:36:52.906808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02909d5f025'
down_revision = '39ca40c39f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.drop_column('chat_history')

    # ### end Alembic commands ###
