"""Add character_class column to player_profiles

Revision ID: e7950a440189
Revises: 03efa8451943
Create Date: 2024-12-07 16:45:45.373051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7950a440189'
down_revision = '03efa8451943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_class', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_column('character_class')

    # ### end Alembic commands ###
