"""
D&D 5e SRD Data
---------------
Curated tables used to randomly generate fully-formed NPC character sheets.
All data is drawn from the Systems Reference Document (SRD 5.1).

Each NPC is generated by:
  1. Picking a species  → grants attribute bonuses + racial features
  2. Picking a class    → grants hit die, saving throws, proficiencies, skills
  3. Rolling ability scores (4d6 drop lowest)
  4. Deriving combat stats (HP, AC, initiative, speed, proficiency bonus)
  5. Picking background → grants skill proficiencies + personality trait pool
  6. Picking alignment
  7. Generating appearance
"""

import random
import math

# ── Species ──────────────────────────────────────────────────────────────────
SPECIES = {
    "Human":      {"bonuses": {"STR":1,"DEX":1,"CON":1,"INT":1,"WIS":1,"CHA":1}, "features": ["Extra Language", "Extra Skill Proficiency"], "speed": 30, "size": "Medium"},
    "Elf":        {"bonuses": {"DEX":2}, "features": ["Darkvision 60ft", "Fey Ancestry", "Trance", "Keen Senses (Perception proficiency)"], "speed": 30, "size": "Medium"},
    "High Elf":   {"bonuses": {"DEX":2,"INT":1}, "features": ["Darkvision 60ft", "Fey Ancestry", "Trance", "Cantrip (INT)"], "speed": 30, "size": "Medium"},
    "Wood Elf":   {"bonuses": {"DEX":2,"WIS":1}, "features": ["Darkvision 60ft", "Fey Ancestry", "Mask of the Wild", "Fleet of Foot (speed 35)"], "speed": 35, "size": "Medium"},
    "Dwarf":      {"bonuses": {"CON":2}, "features": ["Darkvision 60ft", "Dwarven Resilience (poison adv.)", "Stonecunning", "Dwarven Combat Training"], "speed": 25, "size": "Medium"},
    "Halfling":   {"bonuses": {"DEX":2}, "features": ["Lucky (reroll 1s)", "Brave (adv. vs. frightened)", "Halfling Nimbleness"], "speed": 25, "size": "Small"},
    "Dragonborn": {"bonuses": {"STR":2,"CHA":1}, "features": ["Draconic Ancestry (breath weapon)", "Damage Resistance"], "speed": 30, "size": "Medium"},
    "Gnome":      {"bonuses": {"INT":2}, "features": ["Darkvision 60ft", "Gnome Cunning (adv. vs. magic INT/WIS/CHA saves)"], "speed": 25, "size": "Small"},
    "Half-Elf":   {"bonuses": {"CHA":2}, "features": ["Darkvision 60ft", "Fey Ancestry", "Skill Versatility (2 skills)"], "speed": 30, "size": "Medium"},
    "Half-Orc":   {"bonuses": {"STR":2,"CON":1}, "features": ["Darkvision 60ft", "Menacing (Intimidation prof.)", "Relentless Endurance", "Savage Attacks"], "speed": 30, "size": "Medium"},
    "Tiefling":   {"bonuses": {"INT":1,"CHA":2}, "features": ["Darkvision 60ft", "Hellish Resistance (fire)", "Infernal Legacy (Thaumaturgy cantrip)"], "speed": 30, "size": "Medium"},
}

# ── Classes ───────────────────────────────────────────────────────────────────
CLASSES = {
    "Barbarian": {
        "hit_die": 12, "armor": "light+medium+shields", "primary": "STR",
        "saving_throws": ["STR","CON"],
        "skills": ["Animal Handling","Athletics","Intimidation","Nature","Perception","Survival"],
        "num_skills": 2,
        "weapons": [("Greataxe", "+5", "1d12+3 slashing"), ("Handaxe", "+5", "1d6+3 slashing")],
        "features": ["Rage (2/day, +2 dmg)", "Unarmored Defense (CON bonus to AC)"],
    },
    "Bard": {
        "hit_die": 8, "armor": "light", "primary": "CHA",
        "saving_throws": ["DEX","CHA"],
        "skills": ["Acrobatics","Animal Handling","Arcana","Athletics","Deception","History",
                   "Insight","Intimidation","Investigation","Medicine","Nature","Perception",
                   "Performance","Persuasion","Religion","Sleight of Hand","Stealth","Survival"],
        "num_skills": 3,
        "weapons": [("Rapier", "+4", "1d8+2 piercing"), ("Hand Crossbow", "+4", "1d6+2 piercing")],
        "features": ["Bardic Inspiration (d6)", "Jack of All Trades (+half prof to non-prof checks)"],
        "spells": ["Charm Person","Faerie Fire","Healing Word","Thunderwave","Vicious Mockery"],
    },
    "Cleric": {
        "hit_die": 8, "armor": "light+medium+shields", "primary": "WIS",
        "saving_throws": ["WIS","CHA"],
        "skills": ["History","Insight","Medicine","Persuasion","Religion"],
        "num_skills": 2,
        "weapons": [("Mace", "+4", "1d6+2 bludgeoning"), ("Light Crossbow", "+3", "1d8+1 piercing")],
        "features": ["Divine Domain feature", "Spellcasting (WIS)", "Channel Divinity (1/rest)"],
        "spells": ["Cure Wounds","Guiding Bolt","Sacred Flame","Bless","Shield of Faith"],
    },
    "Druid": {
        "hit_die": 8, "armor": "light+medium+shields (non-metal)", "primary": "WIS",
        "saving_throws": ["INT","WIS"],
        "skills": ["Arcana","Animal Handling","Insight","Medicine","Nature","Perception","Religion","Survival"],
        "num_skills": 2,
        "weapons": [("Quarterstaff", "+4", "1d6+2 bludgeoning"), ("Scimitar", "+4", "1d6+2 slashing")],
        "features": ["Wild Shape (CR 1/4, 2/rest)", "Druidic language"],
        "spells": ["Entangle","Healing Word","Shillelagh","Thunderwave","Wild Shape"],
    },
    "Fighter": {
        "hit_die": 10, "armor": "all+shields", "primary": "STR",
        "saving_throws": ["STR","CON"],
        "skills": ["Acrobatics","Animal Handling","Athletics","History","Insight","Intimidation","Perception","Survival"],
        "num_skills": 2,
        "weapons": [("Longsword", "+5", "1d8+3 slashing"), ("Heavy Crossbow", "+4", "1d10+2 piercing")],
        "features": ["Fighting Style", "Second Wind (1d10+lvl HP, 1/rest)", "Action Surge (1/rest)"],
    },
    "Monk": {
        "hit_die": 8, "armor": "none", "primary": "DEX",
        "saving_throws": ["STR","DEX"],
        "skills": ["Acrobatics","Athletics","History","Insight","Religion","Stealth"],
        "num_skills": 2,
        "weapons": [("Unarmed Strike", "+5", "1d4+3 bludgeoning"), ("Shortsword", "+5", "1d6+3 piercing")],
        "features": ["Unarmored Defense (WIS to AC)", "Martial Arts (d4)", "Ki (2 points)"],
    },
    "Paladin": {
        "hit_die": 10, "armor": "all+shields", "primary": "CHA",
        "saving_throws": ["WIS","CHA"],
        "skills": ["Athletics","Insight","Intimidation","Medicine","Persuasion","Religion"],
        "num_skills": 2,
        "weapons": [("Longsword", "+5", "1d8+3 slashing"), ("Shield", "", "AC +2")],
        "features": ["Divine Sense (1+CHA/rest)", "Lay on Hands (5 HP pool)", "Divine Smite"],
        "spells": ["Bless","Cure Wounds","Divine Favor","Shield of Faith"],
    },
    "Ranger": {
        "hit_die": 10, "armor": "light+medium+shields", "primary": "DEX",
        "saving_throws": ["STR","DEX"],
        "skills": ["Animal Handling","Athletics","Insight","Investigation","Nature","Perception","Stealth","Survival"],
        "num_skills": 3,
        "weapons": [("Longbow", "+5", "1d8+3 piercing"), ("Shortsword", "+5", "1d6+3 piercing")],
        "features": ["Favored Enemy", "Natural Explorer", "Hunter's Mark (spell)"],
        "spells": ["Hunter's Mark","Cure Wounds","Fog Cloud"],
    },
    "Rogue": {
        "hit_die": 8, "armor": "light", "primary": "DEX",
        "saving_throws": ["DEX","INT"],
        "skills": ["Acrobatics","Athletics","Deception","Insight","Intimidation","Investigation",
                   "Perception","Performance","Persuasion","Sleight of Hand","Stealth"],
        "num_skills": 4,
        "weapons": [("Rapier", "+5", "1d8+3 piercing"), ("Shortbow", "+5", "1d6+3 piercing")],
        "features": ["Expertise (×2 on 2 skills)", "Sneak Attack (1d6)", "Thieves' Cant", "Cunning Action"],
    },
    "Sorcerer": {
        "hit_die": 6, "armor": "none", "primary": "CHA",
        "saving_throws": ["CON","CHA"],
        "skills": ["Arcana","Deception","Insight","Intimidation","Persuasion","Religion"],
        "num_skills": 2,
        "weapons": [("Dagger", "+4", "1d4+2 piercing"), ("Light Crossbow", "+4", "1d8+2 piercing")],
        "features": ["Sorcerous Origin feature", "Sorcery Points (2)", "Metamagic"],
        "spells": ["Fire Bolt","Mage Armor","Magic Missile","Shield","Thunderwave"],
    },
    "Warlock": {
        "hit_die": 8, "armor": "light", "primary": "CHA",
        "saving_throws": ["WIS","CHA"],
        "skills": ["Arcana","Deception","History","Intimidation","Investigation","Nature","Religion"],
        "num_skills": 2,
        "weapons": [("Dagger", "+4", "1d4+2 piercing"), ("Hand Crossbow", "+4", "1d6+2 piercing")],
        "features": ["Otherworldly Patron feature", "Eldritch Invocations (1)", "Eldritch Blast cantrip"],
        "spells": ["Eldritch Blast","Hex","Charm Person","Arms of Hadar"],
    },
    "Wizard": {
        "hit_die": 6, "armor": "none", "primary": "INT",
        "saving_throws": ["INT","WIS"],
        "skills": ["Arcana","History","Insight","Investigation","Medicine","Religion"],
        "num_skills": 2,
        "weapons": [("Quarterstaff", "+3", "1d6+1 bludgeoning"), ("Dagger", "+4", "1d4+2 piercing")],
        "features": ["Arcane Recovery (1/day, regain spell slots)", "Spellbook"],
        "spells": ["Fire Bolt","Mage Armor","Magic Missile","Shield","Sleep","Detect Magic"],
    },
}

# ── Backgrounds ───────────────────────────────────────────────────────────────
BACKGROUNDS = {
    "Acolyte":     {"skills": ["Insight","Religion"],        "traits": ["I idolize my deity above all else.", "I see omens in every event.", "I quote sacred texts constantly.", "Nothing can shake my faith."]},
    "Criminal":    {"skills": ["Deception","Stealth"],       "traits": ["Always have a contingency plan.", "I don't trust easily — hard to earn, easy to lose.", "I prefer subtlety over brute force.", "Rules are just suggestions for other people."]},
    "Folk Hero":   {"skills": ["Animal Handling","Survival"],"traits": ["I judge by actions, not words.", "Thinking is for other people.", "Standing up to bullies is second nature.", "I have a crude sense of humor."]},
    "Noble":       {"skills": ["History","Persuasion"],      "traits": ["I take great pains with my appearance.", "I have difficulty empathizing with the lower class.", "I'd rather make an ally than an enemy.", "I always keep my composure."]},
    "Sage":        {"skills": ["Arcana","History"],          "traits": ["I've read every book in existence — at least once.", "I speak my mind bluntly.", "I'm dismissive of those who haven't studied.", "I love learning new things above all."]},
    "Soldier":     {"skills": ["Athletics","Intimidation"],  "traits": ["I follow orders, even when it's painful.", "Facing a challenge is better than backing down.", "Obedience is a virtue.", "Hardship only makes me stronger."]},
    "Charlatan":   {"skills": ["Deception","Sleight of Hand"],"traits": ["I fall in and out of love easily.", "Flattery is my best weapon.", "I'm a natural liar.", "I always exaggerate my importance."]},
    "Entertainer": {"skills": ["Acrobatics","Performance"],  "traits": ["I love the crowd's adulation.", "I know a good story for every occasion.", "I change my mood often.", "Scandal follows me everywhere."]},
    "Guild Artisan":{"skills": ["Insight","Persuasion"],     "traits": ["I believe that anything worth doing is worth doing right.", "I'm rude to those who don't appreciate craftsmanship.", "I'm always looking for the best deal.", "My guild comes first."]},
    "Outlander":   {"skills": ["Athletics","Survival"],      "traits": ["I watch over my companions like prey.", "Nature is indifferent; I've learned to be too.", "I place no value on soft city life.", "I am driven by wanderlust."]},
    "Hermit":      {"skills": ["Medicine","Religion"],       "traits": ["I am utterly serene in the face of disaster.", "I am oblivious to etiquette and social norms.", "I connect everything to cosmic significance.", "I'm a profoundly deep thinker."]},
    "Urchin":      {"skills": ["Sleight of Hand","Stealth"], "traits": ["I hide my true self with a mask of humor.", "Stealing is the only way I know.", "I look for the quick fix before the long solution.", "I watch my back obsessively."]},
}

ALIGNMENTS = [
    "Lawful Good","Neutral Good","Chaotic Good",
    "Lawful Neutral","True Neutral","Chaotic Neutral",
    "Lawful Evil","Neutral Evil","Chaotic Evil",
]

GENDERS    = ["Male","Female","Non-binary","Agender"]
EYE_COLORS = ["Brown","Blue","Green","Grey","Amber","Hazel","Silver","Gold","Violet"]
HAIR_COLORS= ["Black","Brown","Blonde","Red","White","Silver","Auburn","Platinum"]
SKIN_TONES = ["Fair","Light","Medium","Tan","Brown","Dark","Ebony","Ashen","Olive"]

BONDS  = [
    "I would die to protect the people I care about.",
    "I owe everything to my mentor.",
    "The guild/order/faith is my true family.",
    "I will do anything to recover a lost artifact of great significance.",
    "Someone I loved was killed. I seek justice.",
    "I protect those who cannot protect themselves.",
]
FLAWS  = [
    "I have a weakness for the vices of the city.",
    "I have trouble trusting anyone but myself.",
    "I am arrogant about my abilities.",
    "Once I set my mind to something, I am slow to change it.",
    "I overlook obvious solutions in favor of complicated ones.",
    "I am quick to assume the worst in people.",
]
IDEALS = [
    "Power. Knowledge is the path to power and domination.",
    "Freedom. Chains, wherever they come from, must be broken.",
    "Greater Good. My gifts are meant to serve the many.",
    "Honor. I don't steal, I don't lie, I face danger directly.",
    "Logic. Emotion must not cloud rational thought.",
    "Change. Life is in constant flux and I embrace it.",
]


# ── Rolling Functions ─────────────────────────────────────────────────────────

def _roll_4d6_drop_lowest() -> int:
    """Roll 4d6, drop the lowest die."""
    rolls = [random.randint(1, 6) for _ in range(4)]
    return sum(sorted(rolls)[1:])


def _modifier(score: int) -> int:
    return math.floor((score - 10) / 2)


def _fmt_mod(m: int) -> str:
    return f"+{m}" if m >= 0 else str(m)


def _proficiency_bonus(level: int = 1) -> int:
    return 2 + ((level - 1) // 4)


# ── Full NPC Generator ────────────────────────────────────────────────────────

def generate_full_npc() -> dict:
    """
    Generate a complete D&D 5e NPC character sheet as a dict
    matching the field structure of the WotC fillable PDF.
    """
    # -- Identity
    species_name = random.choice(list(SPECIES.keys()))
    class_name   = random.choice(list(CLASSES.keys()))
    bg_name      = random.choice(list(BACKGROUNDS.keys()))
    alignment    = random.choice(ALIGNMENTS)
    level        = 1   # NPCs start at level 1

    species = SPECIES[species_name]
    cls     = CLASSES[class_name]
    bg      = BACKGROUNDS[bg_name]
    prof    = _proficiency_bonus(level)

    # -- Ability scores (4d6 drop lowest × 6, assign in order)
    raw = [_roll_4d6_drop_lowest() for _ in range(6)]
    attrs = dict(zip(["STR","DEX","CON","INT","WIS","CHA"], raw))

    # Apply racial bonuses
    for attr, bonus in species["bonuses"].items():
        attrs[attr] = min(20, attrs[attr] + bonus)

    mods = {k: _modifier(v) for k, v in attrs.items()}

    # -- Primary ability modifier (for spell/attack)
    primary     = cls["primary"]
    primary_mod = mods[primary]

    # -- Combat stats
    hit_die     = cls["hit_die"]
    max_hp      = hit_die + mods["CON"]           # Level 1: max die + CON mod
    max_hp      = max(1, max_hp)
    initiative  = mods["DEX"]

    # AC: unarmored default = 10 + DEX mod (class overrides handled by features text)
    ac = 10 + mods["DEX"]
    if "STR" in cls.get("features", []) and class_name == "Barbarian":
        ac = 10 + mods["DEX"] + mods["CON"]
    if class_name == "Monk":
        ac = 10 + mods["DEX"] + mods["WIS"]

    speed = species.get("speed", 30)

    # -- Saving throws (proficient = mod + prof)
    st = {}
    for attr in ["STR","DEX","CON","INT","WIS","CHA"]:
        m = mods[attr]
        st[attr] = m + prof if attr in cls["saving_throws"] else m

    # -- Skills (background grants 2; class grants num_skills)
    all_skills = {
        "Acrobatics":"DEX","Animal Handling":"WIS","Arcana":"INT","Athletics":"STR",
        "Deception":"CHA","History":"INT","Insight":"WIS","Intimidation":"CHA",
        "Investigation":"INT","Medicine":"WIS","Nature":"INT","Perception":"WIS",
        "Performance":"CHA","Persuasion":"CHA","Religion":"INT","Sleight of Hand":"DEX",
        "Stealth":"DEX","Survival":"WIS",
    }
    # Pick class skills (up to num_skills, no duplicates with bg)
    bg_skills   = bg["skills"]
    class_pool  = [s for s in cls["skills"] if s not in bg_skills]
    class_picks = random.sample(class_pool, min(cls["num_skills"], len(class_pool)))
    proficient_skills = set(bg_skills + class_picks)

    skill_values = {}
    for skill, attr in all_skills.items():
        base = mods[attr]
        skill_values[skill] = base + prof if skill in proficient_skills else base

    passive_perception = 10 + skill_values["Perception"]

    # -- Weapons (take first 1-2 from class table)
    weapons = cls.get("weapons", [("Unarmed Strike", "+3", "1d4+1 bludgeoning")])
    weapons = weapons[:2]

    # -- Spells
    spells = cls.get("spells", [])

    # -- Appearance
    gender    = random.choice(GENDERS)
    age       = random.randint(18, 80)
    height_in = random.randint(54, 82)
    h_ft, h_in = divmod(height_in, 12)
    height    = f"{h_ft}'{h_in}\""
    weight    = random.randint(100, 250)
    eyes      = random.choice(EYE_COLORS)
    hair      = random.choice(HAIR_COLORS)
    skin      = random.choice(SKIN_TONES)

    # -- Personality
    personality = random.choice(bg["traits"])
    bond        = random.choice(BONDS)
    flaw        = random.choice(FLAWS)
    ideal       = random.choice(IDEALS)

    # -- Build the output dict matching the PDF field schema
    return {
        # Identity
        "CharacterName":   "",   # filled in by caller
        "RACE":            species_name,
        "CLASS_LEVEL":     f"{class_name} 1",
        "BACKGROUND":      bg_name,
        "ALIGNMENT":       alignment,
        "GENDER":          gender,
        "AGE":             str(age),
        "HEIGHT":          height,
        "WEIGHT":          f"{weight} lb.",
        "EYES":            eyes,
        "HAIR":            hair,
        "SKIN":            skin,
        "SIZE":            species.get("size", "Medium"),

        # Ability scores
        "STR": attrs["STR"], "DEX": attrs["DEX"], "CON": attrs["CON"],
        "INT": attrs["INT"], "WIS": attrs["WIS"], "CHA": attrs["CHA"],

        # Modifiers
        "STRmod":  _fmt_mod(mods["STR"]),
        "DEXmod":  _fmt_mod(mods["DEX"]),
        "CONmod":  _fmt_mod(mods["CON"]),
        "INTmod":  _fmt_mod(mods["INT"]),
        "WISmod":  _fmt_mod(mods["WIS"]),
        "CHamod":  _fmt_mod(mods["CHA"]),

        # Combat
        "AC":       ac,
        "Init":     _fmt_mod(initiative),
        "Speed":    speed,
        "MaxHP":    max_hp,
        "CurrentHP": max_hp,
        "TempHP":   0,
        "HD":       f"1d{hit_die}",
        "ProfBonus":f"+{prof}",

        # Saving throws
        "ST Strength":    _fmt_mod(st["STR"]),
        "ST Dexterity":   _fmt_mod(st["DEX"]),
        "ST Constitution":_fmt_mod(st["CON"]),
        "ST Intelligence":_fmt_mod(st["INT"]),
        "ST Wisdom":      _fmt_mod(st["WIS"]),
        "ST Charisma":    _fmt_mod(st["CHA"]),
        "saving_throw_profs": list(cls["saving_throws"]),

        # Skills (value + whether proficient)
        "skills": {s: {"value": _fmt_mod(v), "proficient": s in proficient_skills}
                   for s, v in skill_values.items()},
        "Passive": passive_perception,

        # Weapons
        "weapons": [{"name": w[0], "atk_bonus": w[1], "damage": w[2]} for w in weapons],

        # Spells
        "spellCastingAbility": primary if spells else "",
        "spells": spells,

        # Racial / Class features
        "racial_features": "; ".join(species["features"]),
        "class_features":  "; ".join(cls.get("features", [])),
        "FeaturesTraits":  "; ".join(cls.get("features", [])),

        # Proficiencies
        "proficient_skills": sorted(list(proficient_skills)),
        "ProficienciesLang": "Common + 1 racial language",
        "armor_proficiency": cls.get("armor", "none"),

        # Personality
        "PersonalityTraits": personality,
        "Bonds":  bond,
        "Flaws":  flaw,
        "Ideals": ideal,

        # Currency (starting gold by class, simplified)
        "GP": random.randint(10, 100),
        "SP": random.randint(0, 9),
        "CP": random.randint(0, 9),
    }
